# Generated by Django 5.1.1 on 2024-09-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'user')], default=1, max_length=10),
        ),
    ]
